/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Database.ConnectDB;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class DoiTacJPanel extends javax.swing.JPanel 
{
    ConnectDB cnn = new ConnectDB();
    /**
     * Creates new form DoiTacJPanel
     */
    public DoiTacJPanel() 
    {
        initComponents();
        layDuLieuDoiTac();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lableMaNPP = new javax.swing.JLabel();
        lableTenNPP = new javax.swing.JLabel();
        lableDiaChi = new javax.swing.JLabel();
        lableSDT = new javax.swing.JLabel();
        lableEmail = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaNPP = new javax.swing.JTextField();
        txtTenNPP = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDt = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChuThich = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbNhaPP = new javax.swing.JTable();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/plus.png"))); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/updated.png"))); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/x-button.png"))); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnThem)
                .addGap(54, 54, 54)
                .addComponent(btnSua)
                .addGap(54, 54, 54)
                .addComponent(btnXoa)
                .addGap(55, 55, 55)
                .addComponent(btnReset)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset)
                    .addComponent(btnSua)
                    .addComponent(btnThem)
                    .addComponent(btnXoa))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhà phân phối", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N

        lableMaNPP.setText("Mã NPP:");

        lableTenNPP.setText("Tên NPP:");

        lableDiaChi.setText("Địa chỉ:");

        lableSDT.setText("SDT:");

        lableEmail.setText("Email:");

        jLabel7.setText("Chú thích:");

        txtMaNPP.setEditable(false);

        txtChuThich.setColumns(20);
        txtChuThich.setRows(5);
        jScrollPane1.setViewportView(txtChuThich);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lableEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lableSDT, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lableDiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lableTenNPP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lableMaNPP, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaNPP)
                    .addComponent(txtTenNPP)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSDt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableMaNPP)
                    .addComponent(txtMaNPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableTenNPP)
                    .addComponent(txtTenNPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableDiaChi)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableSDT)
                    .addComponent(txtSDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chung", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11), new java.awt.Color(255, 0, 51))); // NOI18N

        jtbNhaPP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã NPP", "Tên NPP", "Địa chỉ", "SDT", "Email", "Chú thích"
            }
        ));
        jtbNhaPP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbNhaPPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbNhaPP);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String MaDoiTac, TenDoiTac, DiaChi, SDT, Email, ChuThich;
        MaDoiTac = txtMaNPP.getText();
        TenDoiTac = txtTenNPP.getText();
        DiaChi = txtDiaChi.getText();
        SDT = txtSDt.getText();
        Email = txtEmail.getText();
        ChuThich = txtChuThich.getText();
        String cautruyvan = "insert into NhaPhanPhoi(TenNhaPhanPhoi,DiaChi,SDT,Email,ChuThich) values(N'" + TenDoiTac + "' , N'" + DiaChi + "' ,'" + SDT
        + "','" + Email + "', N'" + ChuThich + "')";
        System.out.println(cautruyvan);
        boolean kiemtra = KiemTraNhapDoiTac(0);
        if (kiemtra) {
            cnn.ExcuteQueryUpdateDB(cautruyvan);
            ResDoiTac();
            ThongBao("Thêm thành công", "Thông báo", 2);
        } else {
            System.out.println("Thất bại");;
        }
        layDuLieuDoiTac();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String MaDoiTac, TenDoiTac, DiaChi, SDT, Email, ChuThich;
        MaDoiTac = txtMaNPP.getText();
        TenDoiTac = txtTenNPP.getText();
        DiaChi = txtDiaChi.getText();
        SDT = txtSDt.getText();
        Email = txtEmail.getText();
        ChuThich = txtChuThich.getText();
        String cautruyvan = "update  NhaPhanPhoi set "
        + " TenNhaPhanPhoi= N'" + TenDoiTac + "' ,DiaChi= N'" + DiaChi + "' ,SDT='" + SDT
        + "',Email='" + Email + "',ChuThich= N'" + ChuThich + "' Where MaNhaPhanPhoi=" + MaDoiTac;
        System.out.println(cautruyvan);
        boolean kiemtra = KiemTraNhapDoiTac(1);
        if (kiemtra) {
            cnn.ExcuteQueryUpdateDB(cautruyvan);
            ResDoiTac();
            ThongBao("Sửa thành công", "Thông báo", 2);

        } else {
            ThongBao("Không thể Thêm Dối Tác", "lỗi", 2);
        }
        layDuLieuDoiTac();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String MaDoiTac = txtMaNPP.getText();
        if (!MaDoiTac.equals("")) {
            String cautruyvan = "delete NhaPhanPhoi where MaNhaPhanPhoi=" + MaDoiTac;
            String ctvKiemThu = "select count(MaPhieuNhap) as SoPhieuNhap"
            + " from NhaPhanPhoi,PhieuNhap where NhaPhanPhoi.MaNhaPhanPhoi=PhieuNhap.MaNhaPhanPhoi"
            + " and  NhaPhanPhoi.MaNhaPhanPhoi=" + MaDoiTac;
            ResultSet rs1 = cnn.ExcuteQueryGetTable(ctvKiemThu);
            System.out.println(ctvKiemThu);
            int so1 = 0;
            try {
                if (rs1.next())
                {
                    so1 = rs1.getInt("SoPhieuNhap");
                    if (rs1.getInt("SoPhieuNhap") == 0)
                    {
                        cnn.ExcuteQueryUpdateDB(cautruyvan);
                        ThongBao("Đã xóa ", "Thông báo", 2);
                        layDuLieuDoiTac();
                        ResDoiTac();
                    } else {
                        ThongBao("không thể xóa bởi Đối Tác đã có " + so1 + " Phiếu Nhập!", "báo lỗi", 2);
                    }
                }
            } catch (SQLException ex) {
                //Logger.getLogger(frmTrangChu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            ThongBao("bạn chưa nhập mã đối tác mà!", "tôi cần sự chăm chỉ của bạn!hãy click vô bảng đã!", 2);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        ResDoiTac();
    }//GEN-LAST:event_btnResetActionPerformed

    private void jtbNhaPPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbNhaPPMouseClicked
        // TODO add your handling code here:
        int viTriDongVuaBam = jtbNhaPP.getSelectedRow();
        txtMaNPP.setText(jtbNhaPP.getValueAt(viTriDongVuaBam, 1).toString());
        txtTenNPP.setText(jtbNhaPP.getValueAt(viTriDongVuaBam, 2).toString());
        txtDiaChi.setText(jtbNhaPP.getValueAt(viTriDongVuaBam, 3).toString());
        txtSDt.setText(jtbNhaPP.getValueAt(viTriDongVuaBam, 4).toString());
        txtEmail.setText(jtbNhaPP.getValueAt(viTriDongVuaBam, 5).toString());
        txtChuThich.setText(jtbNhaPP.getValueAt(viTriDongVuaBam, 6).toString());
    }//GEN-LAST:event_jtbNhaPPMouseClicked
    
    public void ResDoiTac() 
    {
        txtMaNPP.setText("");
        txtTenNPP.setText("");
        txtDiaChi.setText("");
        txtSDt.setText("");
        txtEmail.setText("");
        txtChuThich.setText("");
    }
    public boolean KiemTraNhapDoiTac(int ts) 
    {
        String MaDoiTac,ThongBao="", TenDoiTac, DiaChi, SDT, Email, ChuThich;
        boolean kiemtra=true;
        MaDoiTac = txtMaNPP.getText();
        TenDoiTac = txtTenNPP.getText();
        DiaChi = txtDiaChi.getText();
        SDT = txtSDt.getText();
        Email = txtEmail.getText();
        ChuThich = txtChuThich.getText();
        if (MaDoiTac.equals("") && ts == 1) {
            ThongBao += "bạn chưa chọn khách hàng để lấy  Mã Đối Tác\n";
            lableMaNPP.setForeground(Color.red);
        }
        if (TenDoiTac.equals("")) {
            ThongBao += "bạn chưa Nhập Tên Đối Tác\n";
            lableTenNPP.setForeground(Color.red);
        }
        if (DiaChi.equals("")) {
            lableDiaChi.setForeground(Color.red);
            ThongBao += "bạn chưa Nhập Địa Chỉ\n";
        }
          if (!KiemTraEmail(Email)) {
            lableEmail.setForeground(Color.red);
            ThongBao += "bạn chưa Nhập Đúng Email\n";

        }
        if (SDT.equals("")) {
            lableSDT.setForeground(Color.red);
            ThongBao += "bạn chưa Nhập Số ĐT \n";
        }
        if (ThongBao.equals("")) {
            kiemtra = true;
            lableDiaChi.setForeground(Color.black);
            lableSDT.setForeground(Color.black);
            lableMaNPP.setForeground(Color.black);
            lableTenNPP.setForeground(Color.black);
        } else {
            kiemtra = false;
            ThongBao(ThongBao, "lỗi nhập liệu", 2);
        }
        return kiemtra;
    }
    public boolean KiemTraEmail(String email)
    {
        boolean kq=false;
        String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern v = Pattern.compile(EMAIL_PATTERN);
        Matcher m= v.matcher(email);
        kq=m.matches();
        return kq;
   }
    public void layDuLieuDoiTac() 
    {
        String cautruyvan = "";
        cautruyvan = "select * from NhaPhanPhoi ";
        ResultSet rs = cnn.ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"STT", "Mã", "Tên Đối Tác", "Địa chỉ", "Số DT", "Email", "Chú Thích"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        jtbNhaPP.setModel(tableModel);
        int c = 0;
        try {
            while (rs.next()) {
                c++;
                Object[] item = new Object[7];
                item[0] = c;
                item[1] = rs.getInt("MaNhaPhanPhoi");
                item[2] = rs.getString("TenNhaPhanPhoi");
                item[3] = rs.getString("DiaChi");
                item[4] = rs.getString("SDT");
                item[5] = rs.getString("Email");
                item[6] = rs.getString("ChuThich");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }     
    public void ThongBao(String noiDungThongBao, String tieuDeThongBao, int icon) 
    {
        JOptionPane.showMessageDialog(new JFrame(), noiDungThongBao,
                tieuDeThongBao, icon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtbNhaPP;
    private javax.swing.JLabel lableDiaChi;
    private javax.swing.JLabel lableEmail;
    private javax.swing.JLabel lableMaNPP;
    private javax.swing.JLabel lableSDT;
    private javax.swing.JLabel lableTenNPP;
    private javax.swing.JTextArea txtChuThich;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaNPP;
    private javax.swing.JTextField txtSDt;
    private javax.swing.JTextField txtTenNPP;
    // End of variables declaration//GEN-END:variables
}
