/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Database.ConnectDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author nguye
 */
public class GiamDocJPanel extends javax.swing.JPanel 
{
    ConnectDB cnn = new ConnectDB();
    Calendar cal = Calendar.getInstance();

    int day = cal.get(Calendar.DAY_OF_MONTH);
    int month = cal.get(Calendar.MONTH) + 1;
    int year = cal.get(Calendar.YEAR);
    /**
     * Creates new form GiamDocJPanel
     */
    public GiamDocJPanel() 
    {
        initComponents();
        HiencbbThangNam();
        HienHeSo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGiaMoi = new javax.swing.JTextField();
        txtGiaCu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbbThangSPMoi = new javax.swing.JComboBox<>();
        cbbNamSPMoi = new javax.swing.JComboBox<>();
        cbbNgaySPMoi = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHeSo = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtTenSP = new javax.swing.JTextField();
        txtHSo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnApDung = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGiamGia = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLoaiKhach = new javax.swing.JTextField();
        txtMaLoaiKhachHang = new javax.swing.JTextField();
        txtPhanTram = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtGhiChuLoaiKH = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        btnThemLoai = new javax.swing.JButton();
        txtSuaLoai = new javax.swing.JButton();
        btnXoaLoai = new javax.swing.JButton();
        btnResetLoai = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setText("Giá bán SP mới:");

        jLabel3.setText("Giá bán SP cũ:");

        jLabel4.setText("Ngày nhập Sản Phẩm:");

        cbbThangSPMoi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbThangSPMoiItemStateChanged(evt);
            }
        });

        cbbNamSPMoi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbNamSPMoiItemStateChanged(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ÁP DỤNG TOÀN BỘ SẢN PHẨM");

        btnSua.setText("Áp dụng");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSua)
                .addGap(134, 134, 134))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGiaMoi)
                            .addComponent(txtGiaCu)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cbbNgaySPMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbThangSPMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbNamSPMoi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGiaMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbThangSPMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbNamSPMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbNgaySPMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGiaCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSua)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblHeSo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Sản Phẩm", "Ngày Nhập", "Hệ Số"
            }
        ));
        tblHeSo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHeSoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHeSo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtTenSP.setEditable(false);

        jLabel5.setText("Tên SP:");

        jLabel6.setText("Hệ Số:");

        btnApDung.setText("Áp dụng");
        btnApDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApDungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenSP)
                    .addComponent(txtHSo))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(btnApDung)
                .addGap(77, 77, 77))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(52, 52, 52)
                .addComponent(btnApDung)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sản Phẩm", jPanel2);

        tblGiamGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Loại", "Loại Khách", "Phần trăm giảm", "Ghi Chú"
            }
        ));
        tblGiamGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGiamGiaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblGiamGia);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Mã Loại:");

        jLabel8.setText("Loại Khách");

        jLabel9.setText("Phần trăm giảm:");

        jLabel10.setText("Ghi chú:");

        txtLoaiKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoaiKhachActionPerformed(evt);
            }
        });

        txtMaLoaiKhachHang.setEditable(false);
        txtMaLoaiKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaLoaiKhachHangActionPerformed(evt);
            }
        });

        txtPhanTram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhanTramActionPerformed(evt);
            }
        });

        txtGhiChuLoaiKH.setColumns(20);
        txtGhiChuLoaiKH.setRows(5);
        jScrollPane4.setViewportView(txtGhiChuLoaiKH);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(47, 47, 47)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPhanTram)
                    .addComponent(txtMaLoaiKhachHang)
                    .addComponent(txtLoaiKhach)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtMaLoaiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(txtLoaiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(txtPhanTram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnThemLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/plus.png"))); // NOI18N
        btnThemLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLoaiActionPerformed(evt);
            }
        });

        txtSuaLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/updated.png"))); // NOI18N
        txtSuaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuaLoaiActionPerformed(evt);
            }
        });

        btnXoaLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/x-button.png"))); // NOI18N
        btnXoaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLoaiActionPerformed(evt);
            }
        });

        btnResetLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        btnResetLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetLoaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemLoai)
                    .addComponent(txtSuaLoai)
                    .addComponent(btnXoaLoai)
                    .addComponent(btnResetLoai))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnThemLoai)
                .addGap(18, 18, 18)
                .addComponent(txtSuaLoai)
                .addGap(18, 18, 18)
                .addComponent(btnXoaLoai)
                .addGap(18, 18, 18)
                .addComponent(btnResetLoai)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
        );

        jTabbedPane1.addTab("Khách Hàng", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Nhân Viên", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String GiaSPMoi,GiaSPCu,NgayApDungMoi;
        GiaSPMoi = txtGiaMoi.getText();
        GiaSPCu = txtGiaCu.getText();
        String  ngay, thang, nam;
        ngay = cbbNgaySPMoi.getSelectedItem().toString();
        thang = cbbThangSPMoi.getSelectedItem().toString();
        nam = cbbNamSPMoi.getSelectedItem().toString();
        NgayApDungMoi = nam + "-" + thang + "-" + ngay;
        
        
        String cautruyvan = "update GiamDoc set GiaBanMoi = "+GiaSPMoi+","
                + "NgayApDungMoi = '"+NgayApDungMoi+"',GiaBanCu = "+GiaSPCu+" ";
        cnn.ExcuteQueryUpdateDB(cautruyvan);
        
        String ctv1 = "update SanPham set HeSo = "+Float.valueOf(GiaSPCu)+" "
                + "from SanPham,PhieuNhap,ChiTietPhieuNhap "
                + "where SanPham.MaSanPham = ChiTietPhieuNhap.MaSanPham  "
                + "and PhieuNhap.MaPhieuNhap = ChiTietPhieuNhap.MaPhieuNhap "
                + "and PhieuNhap.NgayNhap < '"+NgayApDungMoi+"'";
        cnn.ExcuteQueryUpdateDB(ctv1);
        
        String ctv2 = "update SanPham set HeSo = "+Float.valueOf(GiaSPMoi)+" "
                + "from SanPham,PhieuNhap,ChiTietPhieuNhap "
                + "where SanPham.MaSanPham = ChiTietPhieuNhap.MaSanPham  "
                + "and PhieuNhap.MaPhieuNhap = ChiTietPhieuNhap.MaPhieuNhap "
                + "and PhieuNhap.NgayNhap >= '"+NgayApDungMoi+"'";
        cnn.ExcuteQueryUpdateDB(ctv2);
        
        
        ThongBao("Áp dụng thanh công", "Thông báo", 2);
        HienHeSo();
    }//GEN-LAST:event_btnSuaActionPerformed
    int tam = 0;
    private void cbbThangSPMoiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbThangSPMoiItemStateChanged
        // TODO add your handling code here:
        String thang = cbbThangSPMoi.getSelectedItem().toString();
        DefaultComboBoxModel cbbmodel = new DefaultComboBoxModel();
        String thanght;
        if (tam == 0) {
            thanght = "0";
        } else {
            thanght = cbbNgaySPMoi.getSelectedItem().toString();
        }
        tam = 1;

        if (thang.equals("4") || thang.equals("6") || thang.equals("9") || thang.equals("11")) {
            cbbNgaySPMoi.setModel(cbbmodel);
            for (int i = 1; i < 31; i++) {
                cbbNgaySPMoi.addItem(String.valueOf(i));
            }
            if (Integer.valueOf(thanght) < 31) {
                cbbNgaySPMoi.setSelectedItem(thanght);
            }
        } else if (thang.equals("1") || thang.equals("3") || thang.equals("5")
            || thang.equals("7") || thang.equals("8") || thang.equals("12") || thang.equals("10")) {

            cbbNgaySPMoi.setModel(cbbmodel);
            for (int i = 1; i < 32; i++) {
                cbbNgaySPMoi.addItem(String.valueOf(i));
            }
            if (Integer.valueOf(thanght) < 32) {
                cbbNgaySPMoi.setSelectedItem(thanght);
            }
        }
        else if((Integer.parseInt(cbbNamSPMoi.getSelectedItem().toString())%4==0&&(Integer.parseInt(cbbNamSPMoi.getSelectedItem().toString())%100!=0)||Integer.parseInt(cbbNamSPMoi.getSelectedItem().toString())%400==0)&&thang.equals("2"))
        {
            cbbNgaySPMoi.setModel(cbbmodel);
            for (int i = 1; i < 30; i++) {
                cbbNgaySPMoi.addItem(String.valueOf(i));
            }
            if (Integer.valueOf(thanght) < 30) {
                cbbNgaySPMoi.setSelectedItem(thanght);
            }
        }
        else {
            cbbNgaySPMoi.setModel(cbbmodel);
            for (int i = 1; i < 29; i++) {
                cbbNgaySPMoi.addItem(String.valueOf(i));
            }
            if (Integer.valueOf(thanght) < 29) {
                cbbNgaySPMoi.setSelectedItem(thanght);
            }
        }
    }//GEN-LAST:event_cbbThangSPMoiItemStateChanged

    private void cbbNamSPMoiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbNamSPMoiItemStateChanged
        // TODO add your handling code here:
        String thang = cbbThangSPMoi.getSelectedItem().toString();
        DefaultComboBoxModel cbbmodel = new DefaultComboBoxModel();
        String thanght;
        if (tam == 0) {
            thanght = "0";
        } else {
            thanght = cbbNgaySPMoi.getSelectedItem().toString();
        }
        tam = 1;

        if (thang.equals("4") || thang.equals("6") || thang.equals("9") || thang.equals("11")) {
            cbbNgaySPMoi.setModel(cbbmodel);
            for (int i = 1; i < 31; i++) {
                cbbNgaySPMoi.addItem(String.valueOf(i));
            }
            if (Integer.valueOf(thanght) < 31) {
                cbbNgaySPMoi.setSelectedItem(thanght);
            }
        } else if (thang.equals("1") || thang.equals("3") || thang.equals("5")
            || thang.equals("7") || thang.equals("8") || thang.equals("12") || thang.equals("10")) {

            cbbNgaySPMoi.setModel(cbbmodel);
            for (int i = 1; i < 32; i++) {
                cbbNgaySPMoi.addItem(String.valueOf(i));
            }
            if (Integer.valueOf(thanght) < 32) {
                cbbNgaySPMoi.setSelectedItem(thanght);
            }
        }
        else if((Integer.parseInt(cbbNamSPMoi.getSelectedItem().toString())%4==0&&(Integer.parseInt(cbbNamSPMoi.getSelectedItem().toString())%100!=0)||Integer.parseInt(cbbNamSPMoi.getSelectedItem().toString())%400==0)&&thang.equals("2"))
        {
            cbbNgaySPMoi.setModel(cbbmodel);
            for (int i = 1; i < 30; i++) {
                cbbNgaySPMoi.addItem(String.valueOf(i));
            }
            if (Integer.valueOf(thanght) < 30) {
                cbbNgaySPMoi.setSelectedItem(thanght);
            }
        }
        else {
            cbbNgaySPMoi.setModel(cbbmodel);
            for (int i = 1; i < 29; i++) {
                cbbNgaySPMoi.addItem(String.valueOf(i));
            }
            if (Integer.valueOf(thanght) < 29) {
                cbbNgaySPMoi.setSelectedItem(thanght);
            }
        }
    }//GEN-LAST:event_cbbNamSPMoiItemStateChanged

    private void tblHeSoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHeSoMouseClicked
        // TODO add your handling code here:
        int viTriDongVuaBam = tblHeSo.getSelectedRow();
        txtTenSP.setText(tblHeSo.getValueAt(viTriDongVuaBam, 1).toString());
        txtHSo.setText(tblHeSo.getValueAt(viTriDongVuaBam, 3).toString());
    }//GEN-LAST:event_tblHeSoMouseClicked

    private void btnApDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApDungActionPerformed
        // TODO add your handling code here:
        String TenSanPham,HeSo;
        TenSanPham = txtTenSP.getText();
        HeSo = txtHSo.getText();
        String cautruyvan = "update SanPham set HeSo = "+HeSo+" where TenSanPham = '"+TenSanPham+"'";
        cnn.ExcuteQueryUpdateDB(cautruyvan);
        System.out.println(cautruyvan);
        ThongBao("Áp dụng thanh công", "Thông báo", 2);
        HienHeSo();
    }//GEN-LAST:event_btnApDungActionPerformed

    private void tblGiamGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGiamGiaMouseClicked
        // TODO add your handling code here:
        int viTriDongVuaBam = tblGiamGia.getSelectedRow();
        txtMaLoaiKhachHang.setText(tblGiamGia.getValueAt(viTriDongVuaBam, 1).toString());
        txtLoaiKhach.setText(tblGiamGia.getValueAt(viTriDongVuaBam, 2).toString());
        txtPhanTram.setText(tblGiamGia.getValueAt(viTriDongVuaBam, 3).toString());
        txtGhiChuLoaiKH.setText(tblGiamGia.getValueAt(viTriDongVuaBam, 4).toString());
    }//GEN-LAST:event_tblGiamGiaMouseClicked

    private void txtLoaiKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoaiKhachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoaiKhachActionPerformed

    private void txtMaLoaiKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaLoaiKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLoaiKhachHangActionPerformed

    private void txtPhanTramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhanTramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhanTramActionPerformed

    private void btnThemLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLoaiActionPerformed
        // TODO add your handling code here:
        String TenLoai,PhanTram,CHuThich;
        TenLoai = txtLoaiKhach.getText();
        PhanTram = txtPhanTram.getText();
        CHuThich = txtGhiChuLoaiKH.getText();
        String cautruyvan = "insert into LoaiKhachHang(TenLoaiKhachHang,PhanTramGiam,GhiChu) values(N'"+TenLoai+"',"+PhanTram+",N'"+CHuThich+"')";
        if(TenLoai.equals(""))
        {
            ThongBao("Vui lòng nhập tên loại KH", "Thông báo", 2);
        }else if(PhanTram.equals(""))
        {
            ThongBao("Vui lòng nhập phần trăm giảm", "Thông báo", 2);
        }else if(!KiemTraChuaChuVaSo(PhanTram))
        {
            ThongBao("Phần trăm là số", "Thông báo", 2);
        }else
        {
            cnn.ExcuteQueryUpdateDB(cautruyvan);
            ThongBao("Đã thêm thành công", "Thông báo", 2);
        }
        layDuLieuLoaiKhachHang();
    }//GEN-LAST:event_btnThemLoaiActionPerformed

    private void txtSuaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuaLoaiActionPerformed
        // TODO add your handling code here:

        String Maloai,TenLoai,PhanTram,CHuThich;
        Maloai =txtMaLoaiKhachHang.getText();
        if(Maloai.equals(""))
        {
            ThongBao("Bạn chưa chọn Loại KH cần sửa", "Thông báo", 2);
        }
        else
        {
            TenLoai = txtLoaiKhach.getText();
            PhanTram = txtPhanTram.getText();
            CHuThich = txtGhiChuLoaiKH.getText();
            String cautruyvan = "update LoaiKhachHang set TenLoaiKhachHang = N'"+TenLoai+"',PhanTramGiam = "+PhanTram+",GhiChu = N'"+CHuThich+"'where MaLoaiKhachHang = "+Maloai;
            cnn.ExcuteQueryUpdateDB(cautruyvan);
            ThongBao("Sửa thành công", "Thông báo", 2);
            layDuLieuLoaiKhachHang();
        }

    }//GEN-LAST:event_txtSuaLoaiActionPerformed

    private void btnXoaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLoaiActionPerformed
        // TODO add your handling code here:

        String TenLoaiKT = null;
        String MaLoaiKH = txtMaLoaiKhachHang.getText();
        if(MaLoaiKH.equals(""))
        {
            ThongBao("Bạn chưa chọn Loại KH cần sửa", "Thông báo", 2);
        }
        else
        {
            String TenLoai = txtLoaiKhach.getText();
            String ctv = "select KhachHang.LoaiKhachHang as Loai from KhachHang,LoaiKhachHang where TenLoaiKhachHang like N'%" + TenLoai + "%'";
            ResultSet rs = cnn.ExcuteQueryGetTable(ctv);
            try {
                while(rs.next())
                {
                    TenLoaiKT = rs.getString("Loai");
                }
            } catch (SQLException ex) {
                Logger.getLogger(KhachHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(TenLoai.equals(TenLoaiKT))
            {
                ThongBao("Không thể xóa vì có KH đang là loại này", "Thông báo", 2);
            }else
            {
                String cautruyvan = "delete LoaiKhachHang where MaLoaiKhachHang = "+MaLoaiKH;
                cnn.ExcuteQueryUpdateDB(cautruyvan);
                ThongBao("Xóa thành công", "Thông báo", 2);
                txtMaLoaiKhachHang.setText("");
                txtLoaiKhach.setText("");
                txtPhanTram.setText("");
                txtGhiChuLoaiKH.setText("");
            }
            layDuLieuLoaiKhachHang();
        }

    }//GEN-LAST:event_btnXoaLoaiActionPerformed

    private void btnResetLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetLoaiActionPerformed
        // TODO add your handling code here:
        txtMaLoaiKhachHang.setText("");
        txtLoaiKhach.setText("");
        txtPhanTram.setText("");
        txtGhiChuLoaiKH.setText("");
    }//GEN-LAST:event_btnResetLoaiActionPerformed
    public void HiencbbThangNam()
    {
        layDuLieuLoaiKhachHang();
        for(int i = 1;i<32;i++)
        {
            
            cbbNgaySPMoi.addItem(String.valueOf(i));
        }
        for (int i = 1; i < 13; i++)
        {
            
            cbbThangSPMoi.addItem(String.valueOf(i));
            
        }
        for (int i = year; i > 2000; i--)
        {
            cbbNamSPMoi.addItem(String.valueOf(i));
            
        }
        cbbNgaySPMoi.setSelectedItem(String.valueOf(day));
        
        cbbThangSPMoi.setSelectedItem(String.valueOf(month));
        cbbNamSPMoi.setSelectedItem(String.valueOf(year));
        
    }
    
    //-------------------------------------------------------------------
    public void HienHeSo()
    {
        String cautruyvan = "select SanPham.TenSanPham,HeSo,PhieuNhap.NgayNhap "
                + "from SanPham,PhieuNhap,ChiTietPhieuNhap "
                + "where SanPham.MaSanPham = ChiTietPhieuNhap.MaSanPham "
                + "and PhieuNhap.MaPhieuNhap = ChiTietPhieuNhap.MaPhieuNhap ";
        ResultSet rs = cnn.ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"STT", "Tên Sản Phẩm","Ngày Nhập","Hệ Số"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblHeSo.setModel(tableModel);
        int c = 0;
        try {
            while (rs.next()) {
                c++;
                Object[] item = new Object[4];
                item[0] = c;
                item[1] = rs.getString("TenSanPham");
                item[2] = rs.getString("NgayNhap");
                item[3] = rs.getString("HeSo"); 
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    
    
    //-------------------------------------------------------------------
    public String GetCbbSelected(JComboBox cbb) 
    {
        Object[] obj = cbb.getSelectedObjects();
        displayvalueModel item = (displayvalueModel) obj[0];
        return item.displayvalue.toString();

    }
    //-------------------------------------------------------------------
    public void ThongBao(String noiDungThongBao, String tieuDeThongBao, int icon) 
    {
        JOptionPane.showMessageDialog(new JFrame(), noiDungThongBao,
                tieuDeThongBao, icon);
    }
    //-------------------------------------------------------------------
    public void setSelectedCombobox(String cbbselected, JComboBox cbb) 
    {
        for (int i = 0; i < cbb.getItemCount(); i++) {
            Object obj = cbb.getItemAt(i);
            if (obj != null) {
                displayvalueModel m = (displayvalueModel) obj;
                if (cbbselected.trim().equals(m.displayMember)) {
                    cbb.setSelectedItem(m);
                }
            }
        }
    }
    public DefaultComboBoxModel LayDuLieucbb(String bang, String Ten, String Ma) 
     {
        String cautruyvan = "select *from " + bang;
        ResultSet rs = cnn.ExcuteQueryGetTable(cautruyvan);
        DefaultComboBoxModel cbbmodel = new DefaultComboBoxModel();
        try {
            while (rs.next()) {
                displayvalueModel valueModel = new displayvalueModel(rs.getString(Ten), rs.getString(Ma));
                cbbmodel.addElement(valueModel);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        return cbbmodel;
    }
    //-------------------------------------------------------------------
    public void layDuLieuLoaiKhachHang() {
        String cautruyvan = "";
        cautruyvan = "select * from LoaiKhachHang";
        ResultSet rs = cnn.ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"STT", "Mã Loại", "Loại Khách Hàng", "Phần Trăm Giảm", "Chú Thích"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblGiamGia.setModel(tableModel);
        int c = 0;
        try {
            while (rs.next()) {
                c++;
                Object[] item = new Object[5];
                item[0] = c;
                item[1] = rs.getInt("MaLoaiKhachHang");
                item[2] = rs.getString("TenLoaiKhachHang");
                item[3] = rs.getString("PhanTramGiam");
              
                item[4] = rs.getString("GhiChu");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    private boolean KiemTraChuaChuVaSo(String chuoi) {
        boolean ketqua = false;
        Pattern p = Pattern.compile("[0-9]");
        Matcher m = p.matcher(chuoi);
        if (!(chuoi == chuoi.toLowerCase())) {
            ketqua = m.find();
        }
        return ketqua;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApDung;
    private javax.swing.JButton btnResetLoai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemLoai;
    private javax.swing.JButton btnXoaLoai;
    private javax.swing.JComboBox<String> cbbNamSPMoi;
    private javax.swing.JComboBox<String> cbbNgaySPMoi;
    private javax.swing.JComboBox<String> cbbThangSPMoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblGiamGia;
    private javax.swing.JTable tblHeSo;
    private javax.swing.JTextArea txtGhiChuLoaiKH;
    private javax.swing.JTextField txtGiaCu;
    private javax.swing.JTextField txtGiaMoi;
    private javax.swing.JTextField txtHSo;
    private javax.swing.JTextField txtLoaiKhach;
    private javax.swing.JTextField txtMaLoaiKhachHang;
    private javax.swing.JTextField txtPhanTram;
    private javax.swing.JButton txtSuaLoai;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
