/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Database.ConnectDB;
import java.awt.Color;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author nguye
 */
public class LuongNhanVienJPanel extends javax.swing.JPanel 
{
    ConnectDB cnn = new ConnectDB();
    Calendar cal = Calendar.getInstance();
    Locale localeEN = new Locale("en", "EN");
    NumberFormat en = NumberFormat.getInstance(localeEN);
    int day = cal.get(Calendar.DAY_OF_MONTH);
    int month = cal.get(Calendar.MONTH) + 1;
    int year = cal.get(Calendar.YEAR);
    /**
     * Creates new form LuongNhanVienJPanel
     */
    public LuongNhanVienJPanel() 
    {
        initComponents();
        HienLuong();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel33 = new javax.swing.JPanel();
        jScrollPane24 = new javax.swing.JScrollPane();
        tblLuongNhanVien_Luong = new javax.swing.JTable();
        jPanel48 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jlbLuongcb = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        txtMaLuong_Luong = new javax.swing.JTextField();
        cbbTenNhanVien_Luong = new javax.swing.JComboBox<>();
        txtLuongCoBan_Luong = new javax.swing.JTextField();
        cbbHeSoLuong_Luong = new javax.swing.JComboBox<>();
        txtTienThuong_Luong = new javax.swing.JTextField();
        txtTongLuong_Luong = new javax.swing.JTextField();
        jScrollPane25 = new javax.swing.JScrollPane();
        txtGhiChu_Luong = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtNgayLap = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbbThan = new javax.swing.JComboBox<>();
        cbbNam = new javax.swing.JComboBox<>();
        chkXem = new javax.swing.JCheckBox();
        btnXuatLuong = new javax.swing.JButton();

        jPanel33.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel33ComponentShown(evt);
            }
        });

        tblLuongNhanVien_Luong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Lương", "Nhân Viên", "Lương Cơ Bản", "Hệ Số", "Tiền Thưởng", "Tổng Lương", "Ngày Nhận", "Ghi Chú"
            }
        ));
        tblLuongNhanVien_Luong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLuongNhanVien_LuongMouseClicked(evt);
            }
        });
        jScrollPane24.setViewportView(tblLuongNhanVien_Luong);

        jLabel57.setText("Mã Lương:");

        jLabel58.setText("Nhân Viên:");

        jlbLuongcb.setText("Lương Cơ Bản:");

        jLabel60.setText("Hệ Số Lương:");

        jLabel61.setText("Tiền Thưởng:");

        jLabel62.setText("Tổng Lương:");

        jLabel63.setText("Ghi Chú:");

        txtMaLuong_Luong.setEditable(false);

        txtLuongCoBan_Luong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLuongCoBan_LuongKeyReleased(evt);
            }
        });

        cbbHeSoLuong_Luong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbHeSoLuong_LuongItemStateChanged(evt);
            }
        });

        txtTienThuong_Luong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienThuong_LuongKeyReleased(evt);
            }
        });

        txtTongLuong_Luong.setEditable(false);

        txtGhiChu_Luong.setColumns(20);
        txtGhiChu_Luong.setRows(5);
        jScrollPane25.setViewportView(txtGhiChu_Luong);

        jLabel1.setText("Ngày lập:");

        txtNgayLap.setEditable(false);

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel48Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel63)
                    .addGroup(jPanel48Layout.createSequentialGroup()
                        .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbLuongcb, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel60, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaLuong_Luong)
                            .addComponent(cbbTenNhanVien_Luong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLuongCoBan_Luong)
                            .addComponent(cbbHeSoLuong_Luong, 0, 220, Short.MAX_VALUE))
                        .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel48Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel61)
                                    .addComponent(jLabel62)))
                            .addGroup(jPanel48Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel1)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTienThuong_Luong)
                    .addComponent(txtTongLuong_Luong)
                    .addComponent(jScrollPane25, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(txtNgayLap))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel48Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jLabel61)
                    .addComponent(txtMaLuong_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienThuong_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(cbbTenNhanVien_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62)
                    .addComponent(txtTongLuong_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbLuongcb)
                    .addComponent(txtLuongCoBan_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel60)
                        .addComponent(cbbHeSoLuong_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel63))
                    .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/plus.png"))); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/updated.png"))); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/x-button.png"))); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnThem)
                .addGap(28, 28, 28)
                .addComponent(btnSua)
                .addGap(28, 28, 28)
                .addComponent(btnXoa)
                .addGap(28, 28, 28)
                .addComponent(btnReset)
                .addGap(22, 22, 22))
        );

        jLabel2.setText("Xem tháng");

        cbbThan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbThanItemStateChanged(evt);
            }
        });

        cbbNam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbNamItemStateChanged(evt);
            }
        });

        chkXem.setText("Xem lương");
        chkXem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkXemItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkXem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cbbThan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkXem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnXuatLuong.setText("Xuất Excel");
        btnXuatLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(252, 252, 252)
                                .addComponent(btnXuatLuong))
                            .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnXuatLuong)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblLuongNhanVien_LuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLuongNhanVien_LuongMouseClicked
        // TODO add your handling code here:
        
        
        int viTriDongVuaBam = tblLuongNhanVien_Luong.getSelectedRow();
        txtMaLuong_Luong.setText(tblLuongNhanVien_Luong.getValueAt(viTriDongVuaBam, 1).toString());
        setSelectedCombobox(tblLuongNhanVien_Luong.getValueAt(viTriDongVuaBam, 2).toString(), cbbTenNhanVien_Luong);
        txtLuongCoBan_Luong.setText(tblLuongNhanVien_Luong.getValueAt(viTriDongVuaBam, 3).toString());
        
        
        String luongnv = tblLuongNhanVien_Luong.getValueAt(viTriDongVuaBam, 4).toString();       
        int luong1 ;
        luong1 = Integer.valueOf(luongnv);
        cbbHeSoLuong_Luong.setSelectedItem(String.valueOf(luong1));
        //setSelectedCombobox(tblLuongNhanVien_Luong.getValueAt(viTriDongVuaBam, 4).toString(), cbbHeSoLuong_Luong);
        
        txtTienThuong_Luong.setText(tblLuongNhanVien_Luong.getValueAt(viTriDongVuaBam, 5).toString());
        txtTongLuong_Luong.setText(tblLuongNhanVien_Luong.getValueAt(viTriDongVuaBam, 6).toString());
        txtNgayLap.setText(tblLuongNhanVien_Luong.getValueAt(viTriDongVuaBam, 7).toString());
        txtGhiChu_Luong.setText(tblLuongNhanVien_Luong.getValueAt(viTriDongVuaBam, 8).toString());
        
    }//GEN-LAST:event_tblLuongNhanVien_LuongMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String MaNV,HeSL,LuongCb,TienThuong,TongLuong,GhiChu;
        MaNV = GetCbbSelected(cbbTenNhanVien_Luong);
        HeSL = cbbHeSoLuong_Luong.getSelectedItem().toString();
        LuongCb = txtLuongCoBan_Luong.getText();
        TienThuong = txtTienThuong_Luong.getText();
        TongLuong = txtTongLuong_Luong.getText();
        GhiChu = txtGhiChu_Luong.getText();
        String cautruyvan = "";
        cautruyvan = "insert into LuongNhanVien(MaNhanVien,HeSoLuong,LuongCoBan,TienThuong,TongLuong,GhiChu)values(" + MaNV + ","+HeSL+","+LuongCb+","+TienThuong+","+TongLuong+",'"+GhiChu+"')";
        System.out.println(cautruyvan);
        boolean kiemtra = KTNhapLuong(0);
        if (kiemtra) {
            cnn.ExcuteQueryUpdateDB(cautruyvan);
            ThongBao("Thêm thành công", "Thông báo", 2);
        } else {
            ThongBao("Thêm thất bại", "Thông báo", 2);
        }
        layDuLieuLuongNhanVien();
        txtMaLuong_Luong.setText("");
        txtGhiChu_Luong.setText("");
        txtLuongCoBan_Luong.setText("");
        txtTienThuong_Luong.setText("");
        txtTongLuong_Luong.setText("");
        cbbTenNhanVien_Luong.setSelectedIndex(0);
        cbbHeSoLuong_Luong.setSelectedIndex(0);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String MaLuong,MaNV,HeSL,LuongCb,TienThuong,TongLuong,GhiChu;
        MaLuong =txtMaLuong_Luong.getText();
        if(MaLuong.equals(""))
        {
            ThongBao("Bạn chưa chọn nhân viên cần sửa", "Thông báo", 2);
        }
        else
        {
            MaNV = GetCbbSelected(cbbTenNhanVien_Luong);
            HeSL = cbbHeSoLuong_Luong.getSelectedItem().toString();
            LuongCb = txtLuongCoBan_Luong.getText();
            TienThuong = txtTienThuong_Luong.getText();
            TongLuong = txtTongLuong_Luong.getText();
            GhiChu = txtGhiChu_Luong.getText();
            String cautruyvan = "";
            cautruyvan = "update LuongNhanVien set MaNhanVien = "+MaNV+",HeSoLuong="+HeSL+",LuongCoBan="+LuongCb+",TienThuong="+TienThuong+",TongLuong="+TongLuong+",GhiChu = N'"+GhiChu+"'where MaLuongNhanVien = "+MaLuong;
            System.out.println(cautruyvan);
            boolean kiemtra = KTNhapLuong(1);
            if (kiemtra) {
                cnn.ExcuteQueryUpdateDB(cautruyvan);
                ThongBao("Sửa thành công", "Thông báo", 2);
            } else {
                ThongBao("Sửa thất bại", "Thông báo", 2);
            }
            layDuLieuLuongNhanVien();
            txtMaLuong_Luong.setText("");
            txtGhiChu_Luong.setText("");
            txtLuongCoBan_Luong.setText("");
            txtTienThuong_Luong.setText("");
            txtTongLuong_Luong.setText("");
            cbbTenNhanVien_Luong.setSelectedIndex(0);
            cbbHeSoLuong_Luong.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String MaLuong;
        MaLuong = txtMaLuong_Luong.getText();
        if(MaLuong.equals(""))
        {
            ThongBao("Bạn chưa chọn nhân viên cần sửa", "Thông báo", 2);
        }
        else{
            String cautruyvan = "delete LuongNhanVien where MaLuongNhanVien = "+MaLuong;
            cnn.ExcuteQueryUpdateDB(cautruyvan);
            ThongBao("Xóa thành công", "Thông báo", 2);
            txtMaLuong_Luong.setText("");
            txtGhiChu_Luong.setText("");
            txtLuongCoBan_Luong.setText("");
            txtTienThuong_Luong.setText("");
            txtTongLuong_Luong.setText("");
            cbbTenNhanVien_Luong.setSelectedIndex(0);
            cbbHeSoLuong_Luong.setSelectedIndex(0);
            layDuLieuLuongNhanVien();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtMaLuong_Luong.setText("");
        txtGhiChu_Luong.setText("");
        txtLuongCoBan_Luong.setText("");
        txtTienThuong_Luong.setText("");
        txtTongLuong_Luong.setText("");
        cbbTenNhanVien_Luong.setSelectedIndex(0);
        cbbHeSoLuong_Luong.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtLuongCoBan_LuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLuongCoBan_LuongKeyReleased
        // TODO add your handling code here:
        int HeSL=1,LuongCb = 0,Thuong=0;
        long Tong;
        HeSL =Integer.valueOf(cbbHeSoLuong_Luong.getSelectedItem().toString());
        try{
            LuongCb = Integer.valueOf(txtLuongCoBan_Luong.getText());    
        }catch(NumberFormatException nn)
        {
            ThongBao("Lương là số", "Thông báo", 2);
        }
        
        try {
            
              
            Thuong = Integer.valueOf(txtTienThuong_Luong.getText());           
            
            System.out.println(HeSL);
        } catch (Exception e) {
        }
        
        Tong = (long) LuongCb * HeSL + Thuong;
        txtTongLuong_Luong.setText(String.valueOf(Tong));
    }//GEN-LAST:event_txtLuongCoBan_LuongKeyReleased

    private void cbbHeSoLuong_LuongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbHeSoLuong_LuongItemStateChanged
        // TODO add your handling code here:
        int HeSL=1,LuongCb = 0,Thuong=0;
        long Tong;
        try {
            LuongCb = Integer.valueOf(txtLuongCoBan_Luong.getText());      
            Thuong = Integer.valueOf(txtTienThuong_Luong.getText());           
            HeSL =Integer.valueOf(cbbHeSoLuong_Luong.getSelectedItem().toString());
            System.out.println(HeSL);
        } catch (Exception e) {
        }
        Tong = (long) LuongCb * HeSL + Thuong;
        txtTongLuong_Luong.setText(String.valueOf(Tong));
    }//GEN-LAST:event_cbbHeSoLuong_LuongItemStateChanged

    private void txtTienThuong_LuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienThuong_LuongKeyReleased
        // TODO add your handling code here:
        int HeSL=1,LuongCb = 0,Thuong=0;
        double Tong;
        HeSL =Integer.valueOf(cbbHeSoLuong_Luong.getSelectedItem().toString());
        try{
            Thuong = Integer.valueOf(txtTienThuong_Luong.getText());     
        }catch(NumberFormatException nn)
        {
            ThongBao("Tiền thưởng là số", "Thông báo", 2);
        }
        try {
            LuongCb = Integer.valueOf(txtLuongCoBan_Luong.getText());      
                  
            
        } catch (Exception e) {
        }
        Tong = (double) LuongCb * HeSL + Thuong;
        txtTongLuong_Luong.setText(String.valueOf(Tong));
    }//GEN-LAST:event_txtTienThuong_LuongKeyReleased

    private void jPanel33ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel33ComponentShown
        // TODO add your handling code here:
        cbbThan.setSelectedItem(String.valueOf(month));
        cbbNam.setSelectedItem(String.valueOf(year));
    }//GEN-LAST:event_jPanel33ComponentShown

    private void cbbThanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbThanItemStateChanged
        // TODO add your handling code here:
        if (chkXem.isSelected())
        {
            XemLuong("YEAR(NgayNhan) = "+cbbNam.getSelectedItem().toString()+"and MONTH(NgayNhan) = "+cbbThan.getSelectedItem().toString());
            txtMaLuong_Luong.setText("");
            txtGhiChu_Luong.setText("");
            txtLuongCoBan_Luong.setText("");
            txtTienThuong_Luong.setText("");
            txtTongLuong_Luong.setText("");
            cbbTenNhanVien_Luong.setSelectedIndex(0);
            cbbHeSoLuong_Luong.setSelectedIndex(0);
        }
        
    }//GEN-LAST:event_cbbThanItemStateChanged

    private void cbbNamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbNamItemStateChanged
        // TODO add your handling code here:
        if (chkXem.isSelected())
        {
            XemLuong("YEAR(NgayNhan) = "+cbbNam.getSelectedItem().toString()+"and MONTH(NgayNhan) = "+cbbThan.getSelectedItem().toString());
            txtMaLuong_Luong.setText("");
            txtGhiChu_Luong.setText("");
            txtLuongCoBan_Luong.setText("");
            txtTienThuong_Luong.setText("");
            txtTongLuong_Luong.setText("");
            cbbTenNhanVien_Luong.setSelectedIndex(0);
            cbbHeSoLuong_Luong.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cbbNamItemStateChanged

    private void chkXemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkXemItemStateChanged
        // TODO add your handling code here:
        if (chkXem.isSelected())
        {
            layDuLieuLuongNhanVien();
        }
        if (!chkXem.isSelected())
        {
            layDuLieuLuongNhanVien();
        }
    }//GEN-LAST:event_chkXemItemStateChanged

    private void btnXuatLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatLuongActionPerformed
        // TODO add your handling code here:
        XuatFileExcel(tblLuongNhanVien_Luong);
    }//GEN-LAST:event_btnXuatLuongActionPerformed
 
    public void HienLuong()
    {
    
        cbbTenNhanVien_Luong.setModel(LayDuLieucbb("NhanVien", "TenNhanVien", "MaNhanVien"));
        cbbHeSoLuong_Luong.setModel(LayDuLieucbb("LuongNhanVien", "HeSoLuong", "MaLuongNhanVien"));
        for (int i = 1; i < 10; i++) 
            {
                cbbHeSoLuong_Luong.addItem(String.valueOf(i));
            }
        for (int i = 1; i < 13; i++)
        {
            cbbThan.addItem(String.valueOf(i));
        }
        for (int i = year; i > 2000; i--)
        {
            cbbNam.addItem(String.valueOf(i));
        }
        cbbThan.setSelectedItem(String.valueOf(month));
        cbbNam.setSelectedItem(String.valueOf(year));
        txtNgayLap.setText(year+"-"+month+"-"+day);
        XemLuong("YEAR(NgayNhan) = "+cbbNam.getSelectedItem().toString()+"and MONTH(NgayNhan) = "+cbbThan.getSelectedItem().toString());
    }
    public void XemLuong(String wherethang)
    {
        String cautruyvan ="select MaLuongNhanVien,NhanVien.TenNhanVien as TenNhanVien,"
                + "LuongCoBan,HeSoLuong,TienThuong,TongLuong,NgayNhan,LuongNhanVien.GhiChu as GhiChu "
                + "from LuongNhanVien,NhanVien where LuongNhanVien.MaNhanVien = NhanVien.MaNhanVien and " +wherethang;
        ResultSet rs = cnn.ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"STT", "Mã Lương", "Tên NV", "Lương Cơ Bản", "Hệ Số", "Tiền Thưởng","Tổng Lương","Ngày Nhận", "Chú Thích"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblLuongNhanVien_Luong.setModel(tableModel);
        int c = 0;
        try {
            while (rs.next()) {
                c++;
                Locale localeVN = new Locale("vi", "VN");
                NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
                Object[] item = new Object[9];
                item[0] = c;
                item[1] = rs.getInt("MaLuongNhanVien");
                item[2] = rs.getString("TenNhanVien");
                long LCB = rs.getLong("LuongCoBan");
                String str = currencyVN.format(LCB);
                item[3] = str;
                item[4] = rs.getLong("HeSoLuong");
                long longNumber = rs.getLong("TienThuong");  
                String str1 = currencyVN.format(longNumber);
                item[5] = str1;
                long longNumber1 = rs.getLong("TongLuong");
                String str2 = currencyVN.format(longNumber1);
                item[6] = str2;
                item[7] = rs.getString("NgayNhan");
                item[8] = rs.getString("GhiChu");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    public boolean KTNhapLuong( int ts)
    {
        String MaLuong,MaNV,LuongCB,HeSL,TongTien,ThongBao="";
        boolean kiemtra= false;
        
        MaLuong = txtMaLuong_Luong.getText();
        MaNV = GetCbbSelected(cbbTenNhanVien_Luong);
        LuongCB = txtLuongCoBan_Luong.getText();
        HeSL= cbbHeSoLuong_Luong.getSelectedItem().toString();
        TongTien = txtTongLuong_Luong.getText();
        if (LuongCB.equals("")) 
        {
            ThongBao += "Bạn chưa nhập lương cơ bản của nhân viên\n";
        }
        if (ThongBao.equals("")) 
        {
            kiemtra = true;
            //lblDiaChi_KhachHang.setForeground(Color.black);
            //lblNgayLap.setForeground(Color.black);
            jlbLuongcb.setForeground(Color.black);
        } else 
        {
            kiemtra = false;
            ThongBao(ThongBao, "lỗi nhập liệu", 2);
        }
        
        return kiemtra;
    }
    public void layDuLieuLuongNhanVien() 
    {
        String cautruyvan = "";
        cautruyvan = "select MaLuongNhanVien,NhanVien.TenNhanVien as TenNhanVien,LuongCoBan,HeSoLuong,TienThuong,TongLuong,NgayNhan,LuongNhanVien.GhiChu as GhiChu from LuongNhanVien,NhanVien where LuongNhanVien.MaNhanVien = NhanVien.MaNhanVien";
        ResultSet rs = cnn.ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"STT", "Mã Lương", "Tên NV", "Lương Cơ Bản", "Hệ Số", "Tiền Thưởng","Tổng Lương","Ngày Nhận", "Chú Thích"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblLuongNhanVien_Luong.setModel(tableModel);
        int c = 0;
        try {
            while (rs.next()) {
                c++;
                Locale localeVN = new Locale("vi", "VN");
                NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
                Object[] item = new Object[9];
                item[0] = c;
                item[1] = rs.getInt("MaLuongNhanVien");
                item[2] = rs.getString("TenNhanVien");
                long LCB = rs.getLong("LuongCoBan");
                String str = currencyVN.format(LCB);
                item[3] = str;
                item[4] = rs.getLong("HeSoLuong");
                long longNumber = rs.getLong("TienThuong");  
                String str1 = currencyVN.format(longNumber);
                item[5] = str1;
                long longNumber1 = rs.getLong("TongLuong");
                String str2 = currencyVN.format(longNumber1);
                item[6] = str2;
                item[7] = rs.getString("NgayNhan");
                item[8] = rs.getString("GhiChu");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }  
    
    
     public DefaultComboBoxModel LayDuLieucbb(String bang, String Ten, String Ma) 
    {
        String cautruyvan = "select *from " + bang;
        ResultSet rs = cnn.ExcuteQueryGetTable(cautruyvan);
        DefaultComboBoxModel cbbmodel = new DefaultComboBoxModel();
        try {
            while (rs.next()) {
                displayvalueModel valueModel = new displayvalueModel(rs.getString(Ten), rs.getString(Ma));
                cbbmodel.addElement(valueModel);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        return cbbmodel;
    }
    //-------------------------------------------------------------------------------------------------------
    public String GetCbbSelected(JComboBox cbb) {
        Object[] obj = cbb.getSelectedObjects();
        displayvalueModel item = (displayvalueModel) obj[0];
        return item.displayvalue.toString();

    }
    //-------------------------------------------------------------------------------------------------------
    public void ThongBao(String noiDungThongBao, String tieuDeThongBao, int icon) 
    {
        JOptionPane.showMessageDialog(new JFrame(), noiDungThongBao,
                tieuDeThongBao, icon);
    }
    //-------------------------------------------------------------------------------------------------------
    public void setSelectedCombobox(String cbbselected, JComboBox cbb) 
    {
        for (int i = 0; i < cbb.getItemCount(); i++) {
            Object obj = cbb.getItemAt(i);
            if (obj != null) {
                displayvalueModel m = (displayvalueModel) obj;
                if (cbbselected.trim().equals(m.displayMember)) {
                    cbb.setSelectedItem(m);
                }
            }
        }
    }
    
    public void XuatFileExcel(JTable table)
    {
        FileOutputStream excelFOU = null;
        BufferedOutputStream excelBOU = null;
        XSSFWorkbook excelJTableExporter = null;
 
        //Choose Location For Saving Excel File
        JFileChooser excelFileChooser = new JFileChooser("F:\\Luu");
//        Change Dilog Box Title
        excelFileChooser.setDialogTitle("Save As");
//        Onliny filter files with these extensions "xls", "xlsx", "xlsm"
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
        excelFileChooser.setFileFilter(fnef);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int excelChooser = excelFileChooser.showSaveDialog(null);
 
//        Check if save button is clicked
        if (excelChooser == JFileChooser.APPROVE_OPTION) {
 
            try {
                //Import excel poi libraries to netbeans
                excelJTableExporter = new XSSFWorkbook();
                XSSFSheet excelSheet = excelJTableExporter.createSheet("JTable Sheet");
                //            Loop to get jtable columns and rows
                for (int i = 0; i < model.getRowCount(); i++) {
                    XSSFRow excelRow = excelSheet.createRow(i);
                    for (int j = 0; j< model.getColumnCount(); j++) 
                    {
                        XSSFCell excelCell = excelRow.createCell(j);                      
                        excelCell.setCellValue(model.getValueAt(i, j).toString());                     
                    }
                }   
                excelFOU = new FileOutputStream(excelFileChooser.getSelectedFile() + ".xlsx");
                excelBOU = new BufferedOutputStream(excelFOU);
                excelJTableExporter.write(excelBOU);
                JOptionPane.showMessageDialog(null, "Xuất file thành công!!!........");
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            } finally {
                try {
                    if (excelBOU != null) {
                        excelBOU.close();
                    }
                    if (excelFOU != null) {
                        excelFOU.close();
                    }
                    if (excelJTableExporter != null) {
                        excelJTableExporter.close();
                    }
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
 
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatLuong;
    private javax.swing.JComboBox<String> cbbHeSoLuong_Luong;
    private javax.swing.JComboBox<String> cbbNam;
    private javax.swing.JComboBox<String> cbbTenNhanVien_Luong;
    private javax.swing.JComboBox<String> cbbThan;
    private javax.swing.JCheckBox chkXem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JLabel jlbLuongcb;
    private javax.swing.JTable tblLuongNhanVien_Luong;
    private javax.swing.JTextArea txtGhiChu_Luong;
    private javax.swing.JTextField txtLuongCoBan_Luong;
    private javax.swing.JTextField txtMaLuong_Luong;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JTextField txtTienThuong_Luong;
    private javax.swing.JTextField txtTongLuong_Luong;
    // End of variables declaration//GEN-END:variables
}
