/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Bean.DanhMucBean;
import Controller.ChuyenManHinhController;
import Database.ConnectDB;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
public class MainJFrame extends javax.swing.JFrame 
{
    ConnectDB cnn = new ConnectDB();
    /**
     * Creates new form MainJFrame
     */
    String tendangnhap;
    int manvkt;
    public MainJFrame() 
    {
        initComponents();
     //   setLocationRelativeTo(null);
    }
    public MainJFrame(String a)
    {
        initComponents();
        tendangnhap = a;
       
        ChaoMung();
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLayout = new javax.swing.JPanel();
        PanelMenu = new javax.swing.JPanel();
        jpnSanPham = new javax.swing.JPanel();
        jlbSanPham = new javax.swing.JLabel();
        jpnKhachHang = new javax.swing.JPanel();
        jlbKhachHang = new javax.swing.JLabel();
        jpnHoaDon = new javax.swing.JPanel();
        jlbHoaDon = new javax.swing.JLabel();
        jpnDoiTac = new javax.swing.JPanel();
        jlbDoiTac = new javax.swing.JLabel();
        jpnNhanVien = new javax.swing.JPanel();
        jlbNhanVien = new javax.swing.JLabel();
        jpnLuongNhanVien = new javax.swing.JPanel();
        jlbLuongNhanVien = new javax.swing.JLabel();
        jpnDiemDanh = new javax.swing.JPanel();
        jlbDiemDanh = new javax.swing.JLabel();
        jpnBaoHanh = new javax.swing.JPanel();
        jlbBaoHanh = new javax.swing.JLabel();
        jpnThongKe = new javax.swing.JPanel();
        jlbThongKe = new javax.swing.JLabel();
        jpnGiamdoc = new javax.swing.JPanel();
        jlbGiamdoc = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TabbleMan = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTenDangNha = new javax.swing.JTextField();
        txtGioiTinh = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtChucVu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlbHinhAnh = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtDoiMK = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trang Chủ");

        PanelMenu.setBackground(new java.awt.Color(255, 255, 255));

        jpnSanPham.setBackground(new java.awt.Color(204, 204, 255));

        jlbSanPham.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/apps.png"))); // NOI18N
        jlbSanPham.setText("Sản Phẩm");

        javax.swing.GroupLayout jpnSanPhamLayout = new javax.swing.GroupLayout(jpnSanPham);
        jpnSanPham.setLayout(jpnSanPhamLayout);
        jpnSanPhamLayout.setHorizontalGroup(
            jpnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnSanPhamLayout.setVerticalGroup(
            jpnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jpnKhachHang.setBackground(new java.awt.Color(204, 204, 255));

        jlbKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/KH (2).png"))); // NOI18N
        jlbKhachHang.setText("Khách hàng");

        javax.swing.GroupLayout jpnKhachHangLayout = new javax.swing.GroupLayout(jpnKhachHang);
        jpnKhachHang.setLayout(jpnKhachHangLayout);
        jpnKhachHangLayout.setHorizontalGroup(
            jpnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnKhachHangLayout.setVerticalGroup(
            jpnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnHoaDon.setBackground(new java.awt.Color(204, 204, 255));

        jlbHoaDon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/HoaDon.png"))); // NOI18N
        jlbHoaDon.setText("Hóa đơn");

        javax.swing.GroupLayout jpnHoaDonLayout = new javax.swing.GroupLayout(jpnHoaDon);
        jpnHoaDon.setLayout(jpnHoaDonLayout);
        jpnHoaDonLayout.setHorizontalGroup(
            jpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnHoaDonLayout.setVerticalGroup(
            jpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnDoiTac.setBackground(new java.awt.Color(204, 204, 255));

        jlbDoiTac.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbDoiTac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDoiTac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/collaboration.png"))); // NOI18N
        jlbDoiTac.setText("Đối tác");

        javax.swing.GroupLayout jpnDoiTacLayout = new javax.swing.GroupLayout(jpnDoiTac);
        jpnDoiTac.setLayout(jpnDoiTacLayout);
        jpnDoiTacLayout.setHorizontalGroup(
            jpnDoiTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbDoiTac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnDoiTacLayout.setVerticalGroup(
            jpnDoiTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbDoiTac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnNhanVien.setBackground(new java.awt.Color(204, 204, 255));

        jlbNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Employee.png"))); // NOI18N
        jlbNhanVien.setText("Nhân viên");

        javax.swing.GroupLayout jpnNhanVienLayout = new javax.swing.GroupLayout(jpnNhanVien);
        jpnNhanVien.setLayout(jpnNhanVienLayout);
        jpnNhanVienLayout.setHorizontalGroup(
            jpnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnNhanVienLayout.setVerticalGroup(
            jpnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnLuongNhanVien.setBackground(new java.awt.Color(204, 204, 255));

        jlbLuongNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbLuongNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbLuongNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/notes (1).png"))); // NOI18N
        jlbLuongNhanVien.setText("Lương");

        javax.swing.GroupLayout jpnLuongNhanVienLayout = new javax.swing.GroupLayout(jpnLuongNhanVien);
        jpnLuongNhanVien.setLayout(jpnLuongNhanVienLayout);
        jpnLuongNhanVienLayout.setHorizontalGroup(
            jpnLuongNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbLuongNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnLuongNhanVienLayout.setVerticalGroup(
            jpnLuongNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbLuongNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnDiemDanh.setBackground(new java.awt.Color(204, 204, 255));

        jlbDiemDanh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbDiemDanh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDiemDanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reputation.png"))); // NOI18N
        jlbDiemDanh.setText("Điểm danh");

        javax.swing.GroupLayout jpnDiemDanhLayout = new javax.swing.GroupLayout(jpnDiemDanh);
        jpnDiemDanh.setLayout(jpnDiemDanhLayout);
        jpnDiemDanhLayout.setHorizontalGroup(
            jpnDiemDanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbDiemDanh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnDiemDanhLayout.setVerticalGroup(
            jpnDiemDanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbDiemDanh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnBaoHanh.setBackground(new java.awt.Color(204, 204, 255));

        jlbBaoHanh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbBaoHanh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBaoHanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/protection.png"))); // NOI18N
        jlbBaoHanh.setText("Bảo hành");

        javax.swing.GroupLayout jpnBaoHanhLayout = new javax.swing.GroupLayout(jpnBaoHanh);
        jpnBaoHanh.setLayout(jpnBaoHanhLayout);
        jpnBaoHanhLayout.setHorizontalGroup(
            jpnBaoHanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbBaoHanh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnBaoHanhLayout.setVerticalGroup(
            jpnBaoHanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbBaoHanh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnThongKe.setBackground(new java.awt.Color(204, 204, 255));

        jlbThongKe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/graph (1).png"))); // NOI18N
        jlbThongKe.setText("Thống kê");

        javax.swing.GroupLayout jpnThongKeLayout = new javax.swing.GroupLayout(jpnThongKe);
        jpnThongKe.setLayout(jpnThongKeLayout);
        jpnThongKeLayout.setHorizontalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnThongKeLayout.setVerticalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongKeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jlbThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        jpnGiamdoc.setBackground(new java.awt.Color(204, 204, 255));

        jlbGiamdoc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbGiamdoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbGiamdoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/unauthorized-person.png"))); // NOI18N
        jlbGiamdoc.setText("Giám đốc");

        javax.swing.GroupLayout jpnGiamdocLayout = new javax.swing.GroupLayout(jpnGiamdoc);
        jpnGiamdoc.setLayout(jpnGiamdocLayout);
        jpnGiamdocLayout.setHorizontalGroup(
            jpnGiamdocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbGiamdoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnGiamdocLayout.setVerticalGroup(
            jpnGiamdocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbGiamdoc, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1111111.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnDoiTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnDiemDanh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnLuongNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnBaoHanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnGiamdoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnDoiTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnDiemDanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnLuongNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jpnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnGiamdoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        TabbleMan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Tên:");

        txtTenDangNha.setEditable(false);
        txtTenDangNha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtGioiTinh.setEditable(false);
        txtGioiTinh.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNgaySinh.setEditable(false);
        txtNgaySinh.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtChucVu.setEditable(false);
        txtChucVu.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setText("Giới tính:");

        jLabel5.setText("Ngày sinh:");

        jLabel6.setText("Chức vụ:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenDangNha, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(txtTenDangNha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CHÀO MỪNG BẠN ĐÃ ĐĂNG NHẬP VÀO HỆ THỐNG");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel7)
                .addGap(210, 210, 210))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jlbHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        txtDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/file.png"))); // NOI18N
        txtDoiMK.setText("Đổi Mật Khẩu");
        txtDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoiMKActionPerformed(evt);
            }
        });

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit (2).png"))); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Employee.png"))); // NOI18N
        jButton1.setText("Cá nhân");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDoiMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(152, 152, 152))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(171, 171, 171))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(53, 53, 53)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );

        TabbleMan.addTab("Trang chủ", new javax.swing.ImageIcon(getClass().getResource("/Image/homepage.png")), jPanel1); // NOI18N

        jpnView.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1117, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TabbleMan.addTab("Màn tương tác", new javax.swing.ImageIcon(getClass().getResource("/Image/television.png")), jpnView); // NOI18N

        javax.swing.GroupLayout PanelLayoutLayout = new javax.swing.GroupLayout(PanelLayout);
        PanelLayout.setLayout(PanelLayoutLayout);
        PanelLayoutLayout.setHorizontalGroup(
            PanelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayoutLayout.createSequentialGroup()
                .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbleMan))
        );
        PanelLayoutLayout.setVerticalGroup(
            PanelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbleMan)
            .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoiMKActionPerformed
        // TODO add your handling code here:
        frmDoimatkhau doi = new frmDoimatkhau();
        doi.show();
    }//GEN-LAST:event_txtDoiMKActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
       DangNhapJFrame dn = new DangNhapJFrame();
       dn.show();
       this.dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CaNhanJFrame cn = new CaNhanJFrame( KiemTraTENNV(tendangnhap));
        
        cn.show();
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    int ktten;
    //Lấy mã nhân viên theo tên đăng nhập
    public int KiemTraTENNV(String tendn) 
    {
        
        String cautruyvan = "select * from Users where TenDangNhap= '" + tendn + "'";
        //System.out.println(cautruyvan);
        ResultSet rs = cnn.ExcuteQueryGetTable(cautruyvan);
        try {
            if (rs.next()) 
            {
                
                ktten = rs.getInt("MaNhanVien");
                
            }
        } catch (SQLException ex) 
        {
            System.out.println("lỗi đăng nhập");
        }
        return ktten; //trả về Mã NV
        
    }
    
    
    String tenvuadckt,ngay,gt,cv,hinhanh;
    
    public void ChaoMung()
    {
        manvkt = KiemTraTENNV(tendangnhap); //gắn MaNV vào biến manvkt
        HDJPanel hd = new HDJPanel(manvkt);
        
        PhanQuyen(manvkt);
        String ctv ="select * from NhanVien,ChucVu where NhanVien.ChucVu=ChucVu.MaChucVu and MaNhanVien = '"+manvkt+"'";
        
        ResultSet rs1 = cnn.ExcuteQueryGetTable(ctv);
        try
        {
            if(rs1.next())
            {
                tenvuadckt = rs1.getString("TenNhanVien"); //Lấy tên nhân viên               
                txtTenDangNha.setText(String.valueOf(tenvuadckt));
                ngay = rs1.getString("NgaySinh");
                txtNgaySinh.setText(ngay);
                if (rs1.getInt("GioiTinh") == 1) {
                    txtGioiTinh.setText("Nam");
                } else {
                    txtGioiTinh.setText("Nữ");
                }
                
                cv = rs1.getString("TenChucVu");
                txtChucVu.setText(cv);
                hinhanh = rs1.getString("Image");
                setLabelImage(hinhanh);
                
            }
            
        }catch (SQLException ex)
        {
            System.out.println("lỗi đăng nhập");
        }
    }
    ImageIcon icon;
    public void setLabelImage(String imagePath) 
    {
        if (imagePath == null) {
            imagePath = "D:\\Image\\CaNhan\\2.jpg";
        }
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imagePath));
        } catch (IOException e) {

        }
        icon = new ImageIcon(img.getScaledInstance(jlbHinhAnh.getWidth(),jlbHinhAnh.getHeight(), Image.SCALE_SMOOTH));

        jlbHinhAnh.setIcon(icon);
    }
    public void PhanQuyen(int ma)
    {
        
        String TenQuyen = null;
        String cautruyvan = "Select * from Users where MaNhanVien = "+ma;
        ResultSet rs = cnn.ExcuteQueryGetTable(cautruyvan);
        try {
            while (rs.next())
            {
                int MaQuyen = rs.getInt("Quyen");
                String ctv = "select * from Quyen where MaQuyen = "+ MaQuyen;
                ResultSet rs1 = cnn.ExcuteQueryGetTable(ctv);
                while(rs1.next())
                {
                    TenQuyen = rs1.getString("TenQuyen");
                    System.out.println(TenQuyen);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(TenQuyen.equals("Quản Trị Viên"))
        {
            List<DanhMucBean> listItem = new ArrayList<>();
            listItem.add(new DanhMucBean("ChiTietThongKe", jpnThongKe, jlbThongKe));
            listItem.add(new DanhMucBean("SanPham", jpnSanPham, jlbSanPham));
            listItem.add(new DanhMucBean("KhachHang", jpnKhachHang, jlbKhachHang));
            listItem.add(new DanhMucBean("HoaDon", jpnHoaDon, jlbHoaDon));
            listItem.add(new DanhMucBean("DoiTac", jpnDoiTac, jlbDoiTac));
            listItem.add(new DanhMucBean("NhanVien", jpnNhanVien, jlbNhanVien));
            listItem.add(new DanhMucBean("LuongNhanVien", jpnLuongNhanVien, jlbLuongNhanVien)); 
            listItem.add(new DanhMucBean("DiemDanh", jpnDiemDanh, jlbDiemDanh));
            listItem.add(new DanhMucBean("BaoHanh", jpnBaoHanh, jlbBaoHanh));
            listItem.add(new DanhMucBean("GiamDoc", jpnGiamdoc, jlbGiamdoc));
            ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);
            controller.setView(jpnSanPham, jlbSanPham);
            controller.setEnvent(listItem);
        } else if(TenQuyen.equals("Kế Toán"))
        {
            List<DanhMucBean> listItem = new ArrayList<>();
            listItem.add(new DanhMucBean("ChiTietThongKe", jpnThongKe, jlbThongKe));
            listItem.add(new DanhMucBean("SanPham", jpnSanPham, jlbSanPham));
            listItem.add(new DanhMucBean("LuongNhanVien", jpnLuongNhanVien, jlbLuongNhanVien)); 
            jpnKhachHang.setBackground(new Color(51,0,0));
            jpnHoaDon.setBackground(new Color(51,0,0));
            jpnDoiTac.setBackground(new Color(51,0,0));
            jpnNhanVien.setBackground(new Color(51,0,0));
            jpnDiemDanh.setBackground(new Color(51,0,0));
            ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);
            controller.setView(jpnSanPham, jlbSanPham);
            controller.setEnvent(listItem);
        }else if(TenQuyen.equals("Thu Ngân"))
        {
            List<DanhMucBean> listItem = new ArrayList<>();
            listItem.add(new DanhMucBean("KhachHang", jpnKhachHang, jlbKhachHang));
            listItem.add(new DanhMucBean("HoaDon", jpnHoaDon, jlbHoaDon));
            listItem.add(new DanhMucBean("BaoHanh", jpnBaoHanh, jlbBaoHanh));
            jpnThongKe.setBackground(new Color(51,0,0));
            jpnSanPham.setBackground(new Color(51,0,0));
            jpnLuongNhanVien.setBackground(new Color(51,0,0));
            jpnNhanVien.setBackground(new Color(51,0,0));
            jpnDoiTac.setBackground(new Color(51,0,0));
            jpnDiemDanh.setBackground(new Color(51,0,0));
            ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);
            controller.setView1(jpnKhachHang, jlbKhachHang);
            controller.setEnvent(listItem);
        }else if(TenQuyen.equals("Giám Đốc"))
        {
            List<DanhMucBean> listItem = new ArrayList<>();
            listItem.add(new DanhMucBean("ChiTietThongKe", jpnThongKe, jlbThongKe));
            listItem.add(new DanhMucBean("DoiTac", jpnDoiTac, jlbDoiTac));
            jpnSanPham.setBackground(new Color(51,0,0));
            jpnHoaDon.setBackground(new Color(51,0,0));
            jpnLuongNhanVien.setBackground(new Color(51,0,0));
            jpnKhachHang.setBackground(new Color(51,0,0));
            jpnNhanVien.setBackground(new Color(51,0,0));
            jpnDiemDanh.setBackground(new Color(51,0,0));
            ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);
            controller.setView2(jpnThongKe, jlbThongKe);
            controller.setEnvent(listItem);
        }else if(TenQuyen.equals("Nhân Sự"))
        {
            List<DanhMucBean> listItem = new ArrayList<>();
            listItem.add(new DanhMucBean("NhanVien", jpnNhanVien, jlbNhanVien));
            listItem.add(new DanhMucBean("DiemDanh", jpnDiemDanh, jlbDiemDanh));
            jpnSanPham.setBackground(new Color(51,0,0));
            jpnHoaDon.setBackground(new Color(51,0,0));
            jpnLuongNhanVien.setBackground(new Color(51,0,0));
            jpnKhachHang.setBackground(new Color(51,0,0));
            jpnThongKe.setBackground(new Color(51,0,0));
            jpnDoiTac.setBackground(new Color(51,0,0));
            ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);
            controller.setView3(jpnNhanVien, jlbNhanVien);
            controller.setEnvent(listItem);
        }  
    }
    
    
    public void ThongBao(String noiDungThongBao, String tieuDeThongBao, int icon) 
    {
        JOptionPane.showMessageDialog(new JFrame(), noiDungThongBao,
                tieuDeThongBao, icon);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLayout;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JTabbedPane TabbleMan;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jlbBaoHanh;
    private javax.swing.JLabel jlbDiemDanh;
    private javax.swing.JLabel jlbDoiTac;
    private javax.swing.JLabel jlbGiamdoc;
    private javax.swing.JLabel jlbHinhAnh;
    private javax.swing.JLabel jlbHoaDon;
    private javax.swing.JLabel jlbKhachHang;
    private javax.swing.JLabel jlbLuongNhanVien;
    private javax.swing.JLabel jlbNhanVien;
    private javax.swing.JLabel jlbSanPham;
    private javax.swing.JLabel jlbThongKe;
    private javax.swing.JPanel jpnBaoHanh;
    private javax.swing.JPanel jpnDiemDanh;
    private javax.swing.JPanel jpnDoiTac;
    private javax.swing.JPanel jpnGiamdoc;
    private javax.swing.JPanel jpnHoaDon;
    private javax.swing.JPanel jpnKhachHang;
    private javax.swing.JPanel jpnLuongNhanVien;
    private javax.swing.JPanel jpnNhanVien;
    private javax.swing.JPanel jpnSanPham;
    private javax.swing.JPanel jpnThongKe;
    private javax.swing.JPanel jpnView;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JButton txtDoiMK;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtTenDangNha;
    // End of variables declaration//GEN-END:variables
}
